---
title: "WCOA-2"
output: pdf_document
date: "2024-06-12"
---

```{r}
#load libraries for coding
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readxl)
```

--------------------------------------------------------------------------------

```{r}
#cleaning calibrated WCOA 2013 data (part 1)
wcoa2 <- read_excel("~/Desktop/NOAA/NOAA_Repository/WCOA/WCOA-2/32P020130821_GLODAP.xlsx") %>% 
  slice(-1)

colnames(wcoa2) <- wcoa2[1, ]

wcoa2 <- wcoa2 %>% 
  slice(-1, -2, -407) %>% 
  janitor::clean_names() %>% 
  filter(oxygen > 0 | ctdoxy > 0) %>%
  filter(oxygen_flag_w == 1 | oxygen_flag_w == 2 | oxygen_flag_w == 6) %>% 
  mutate(oxygen = if_else(oxygen < 0, NA, oxygen)) %>% 
  mutate(ctdoxy = if_else(ctdoxy < 0, NA, ctdoxy)) %>%
  mutate(date = dmy(str_glue("{day}, {month}, {year}"))) %>%
  select(stnnbr, oxygen, ctdoxy, latitude, longitude, ctdtmp, ctdsal, ctdprs, date) %>% 
  mutate(cruise = rep("WCOA 2013", n())) %>%
  mutate(across(1:8, as.numeric))

#cleaning calibrated WCOA 2013 data (part 2)
wcoa22 <- read_excel("~/Desktop/NOAA/NOAA_Repository/WCOA/WCOA-2/317W20130803.xlsx") %>% 
  slice(-c(1:28), -30)

colnames(wcoa22) <- wcoa22[1, ]
  
wcoa22 <- wcoa22 %>% 
  slice(-1, -570) %>% 
  janitor::clean_names() %>% 
  filter(oxygen > 0 | ctdoxy > 0) %>%
  filter(oxygen_flag_w == 1 | oxygen_flag_w == 2 | oxygen_flag_w == 6) %>%
  mutate(oxygen = if_else(oxygen < 0, NA, oxygen)) %>% 
  mutate(ctdoxy = if_else(ctdoxy < 0, NA, ctdoxy)) %>%
  select(stnnbr, oxygen, ctdoxy, latitude, longitude, ctdtmp, ctdsal, ctdprs, date) %>% 
  mutate(cruise = rep("WCOA5", n())) %>%
  mutate(across(1:8, as.numeric)) %>% 
  mutate(date = ymd(date))

#joining WCOA 2013 data
wcoa21 <- rbind(wcoa2, wcoa22)

write_csv(wcoa21, "~/Desktop/NOAA/NOAA_Repository/WCOA/WCOA-2/WCOA-2013-CLEAN.csv") # --> WCOA-2013-CLEAN
```




--------------------------------------------------------------------------------

