---
title: "WCOA-3"
output: pdf_document
date: "2024-06-12"
---

```{r}
#load libraries for coding
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readxl)
```

--------------------------------------------------------------------------------

```{r}
#cleaning calibrated WCOA 2016 data
wcoa3 <- read_excel("~/Desktop/NOAA/NOAA_Repository/WCOA/WCOA-3/W05_WCOA2016R_djg_v2.xlsx")

wcoa3 <- wcoa3 %>% 
  mutate(date = dmy(str_glue("{DAY_UTC}, {MONTH_UTC}, {YEAR_UTC}"))) %>% 
  janitor::clean_names() %>% 
  rename(stnnbr = station_id, ctdprs = ctdpressure_dbar, oxygen = oxygen_umol_kg, 
         latitude = latitude_decimal, longitude = longitude_decimal, ctdoxy = ctdoxygen_umol_kg, 
         ctdtmp = ctdtmp_its90_deg_c, ctdsal = salinity_pss78) %>% 
  filter(oxygen > 0 | ctdoxy > 0) %>%
  filter(oxygen_flag == 1 | oxygen_flag == 2 | oxygen_flag == 6) %>%
  filter(oxygen != 0 & oxygen < 8000) %>% 
  mutate(oxygen = if_else(oxygen < 0, NA, oxygen)) %>% 
  mutate(ctdoxy = if_else(ctdoxy < 0, NA, ctdoxy)) %>%
  select(stnnbr, oxygen, ctdoxy, latitude, longitude, ctdtmp, ctdsal, ctdprs, date) %>% 
  mutate(cruise = rep("WCOA 2016", n())) %>%
  mutate(across(1:8, as.numeric))

write_csv(wcoa3, "~/Desktop/NOAA/NOAA_Repository/WCOA/WCOA-3/WCOA-2016-CLEAN.csv") # --> WCOA-2016-CLEAN
```

--------------------------------------------------------------------------------
