---
title: "ECOA-2"
output: pdf_document
date: "2024-06-12"
---

```{r}
#load libraries for code
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readxl)
```

--------------------------------------------------------------------------------

```{r}
#ECOA2 calibrated data cleaning
ecoa2 <- read_excel("~/Desktop/NOAA/NOAA_Repository/ECOA/ECOA-2/33HH20180625_GLODAP.xlsx") %>% 
  slice(-1)

colnames(ecoa2) <- ecoa2[1, ]

ecoa2 <- ecoa2 %>% 
  slice(-1, -2, -3277) %>% 
  janitor::clean_names() %>% 
  mutate(date = dmy(str_glue("{day}, {month}, {year}"))) %>% 
  mutate(across(2:35, as.numeric)) %>% 
  mutate(ctdprs2 = round(ctdprs, 0), latitude = round(latitude, 1), longitude = round(longitude, 1)) %>% 
  rename(Station = stnnbr) %>% 
  mutate(depth_change = ctdprs - lag(ctdprs, n = 1)) %>% 
  filter(depth_change != 0)
```

```{r}
#ECOA2 uncalibrated data cleaning
ecoa2_raw <- read_excel("~/Desktop/NOAA/NOAA_Repository/ECOA/ECOA-2/ECOA2_master_sheet_discrete_NCEI.xlsx") %>% 
  slice(-1) %>% 
  janitor::clean_names() %>%
  mutate(across(1:57, as.numeric)) %>% 
  mutate(raw_oxygen = ctd_o2_2_conc, latitude = round(latitude, 1), longitude = round(longitude, 1)) %>% 
  rename(ctdprs = pressure, Station = station_number) %>% 
  drop_na(Station)
```



```{r}
#joining data
joined_ecoa2 <- left_join(ecoa2_raw, ecoa2, by = c("Station", "ctdprs", "oxygen")) %>% 
  mutate(oxygen = ifelse(oxygen < 0, NA, oxygen)) %>% 
  mutate(corrected_diff = abs(ctdoxy - oxygen), uncorrected_diff = abs(raw_oxygen - oxygen), cruise = rep("ECOA 2018", n())) %>% 
  dplyr::select(raw_oxygen, ctdtmp, ctdprs, ctdsal, oxygen, ctdoxy, Station, latitude.x, longitude.x, cruise) %>% 
  rename(latitude = latitude.x, longitude = longitude.x) %>% 
  drop_na(oxygen, ctdoxy, raw_oxygen) 

write_csv(joined_ecoa2, "~/Desktop/NOAA/NOAA_Repository/ECOA/ECOA-2/ECOA-2-CLEAN.csv") # --> ECOA-2-CLEAN
```

--------------------------------------------------------------------------------

