---
title: "Gordon Gunter"
output: pdf_document
date: "2024-06-12"
---

```{r}
#load libraries
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readxl)
```

-------------------------------------------------------------------------------


```{r}
gunter1 <- read_excel("~/NOAA Work/East Coast/Gordon Gunter/33GG20130609_BT.xlsx") %>% 
  slice(-c(1:29), -31)

colnames(gunter1) <- gunter1[1, ]

gunter1 <- gunter1 %>% 
  slice(-1, -94) %>% 
  janitor::clean_names() %>% 
  mutate(across(10:32, as.numeric))

# Gunter 2
Gunter2 <- read_excel("~/NOAA Work/East Coast/Gordon Gunter/33GG20131114_BT.xlsx") %>% 
  slice(-c(1:29), -31)

colnames(Gunter2) <- Gunter2[1, ]

Gunter2 <- Gunter2 %>% 
  slice(-1, -78) %>% 
  janitor::clean_names() %>% 
  mutate(across(10:32, as.numeric))

gunter <- rbind(gunter1, Gunter2)

gunter <- gunter %>% 
  mutate(date = if_else(nchar(date) < 8, paste0("0", date), date)) %>% 
  mutate(date = if_else(row_number() %in% 1:92, dmy(date), ymd(date))) %>% 
  filter(ctdoxy > 0) %>%
  mutate(oxygen = rep(NA, n()), stnnbr = rep(NA, n())) %>% 
  select(stnnbr, oxygen, ctdoxy, latitude, longitude, ctdtmp, ctdsal, ctdprs, date) %>% 
  mutate(cruise = rep("Gunter", n())) %>%
  mutate(across(1:8, as.numeric))

write_csv(gunter, "~/NOAA Work/East Coast/Gordon Gunter/Gunter-CLEAN.csv")
```

--------------------------------------------------------------------------------

```{r}
gunter %>% 
  group_by(latitude, longitude) %>% 
  count(n())
```

```{r}
prof1 <- gunter %>% 
  filter(latitude == 42.3150, longitude == -70.2783) 
```

```{r}
ggplot() +
  geom_smooth(data = prof1, aes(x = ctdoxy, y = ctdprs), orientation = "y", color = "red") +
  scale_y_reverse() +
  xlim(0, 300) + 
  labs(y = "depth (m)", x = "oxygen (umol/kg)")
```                                                                 

```{r}
prof1 %>%
    mutate(oxychange = abs(ctdoxy - lag(ctdoxy, n = 1))) %>% 
    mutate(depthchange = abs(ctdprs - lag(ctdprs, n = 1))) %>% 
    mutate(ROC = round(oxychange/depthchange, 3)) %>% 
    select(ctdprs, ROC, ctdoxy)
```

--------------------------------------------------------------------------------

```{r}
ggplot() +
  geom_smooth(data = ecoa1, aes(x = ctdoxy, y = ctdprs), orientation = "y", color = "red") +
  scale_y_reverse() +
  xlim(0, 300) +
  labs(y = "depth (m)", x = "oxygen (umol/kg)")
```

```{r}
mean(abs(ecoa1$oxygen - ecoa1$ctdoxy), na.rm = TRUE) # Will not work because no titration data
```

