---
title: "GOMECC-2"
output: pdf_document
date: "2024-06-12"
---

```{r}
#load libraries for coding
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readxl)
```

-------------------------------------------------------------------------------

```{r}
#cleaning GOMECC2 calibrated data
gom2_gom <- read_excel("~/Desktop/NOAA/NOAA_Repository/GOMECC/GOMECC-2/GOMECC2_station_data-1.xlsx") %>% 
  slice(-1) %>% 
  janitor::clean_names() %>% 
  filter(oxygen > 0 | ctdoxy > 0) %>% 
  filter(oxygen_flag_w == 1 | oxygen_flag_w == 2 | oxygen_flag_w == 6) %>% 
  mutate(oxygen = if_else(oxygen < 0, NA, oxygen)) %>% 
  mutate(ctdoxy = if_else(ctdoxy < 0, NA, ctdoxy)) %>%
  select(stnnbr, oxygen, ctdoxy, latitude, longitude, ctdtmp, ctdsal, ctdprs, date) %>% 
  mutate(across(1:8, as.numeric)) %>% 
  mutate(cruise = rep("GOMECC2", n()))

write_csv(gom2_gom, "~/Desktop/NOAA/NOAA_Repository/GOMECC/GOMECC-2/GOMECC-2-CLEAN.csv") # --> GOMECC-2-CLEAN
```

--------------------------------------------------------------------------------
