---
title: "WCOA-5"
output: pdf_document
date: "2024-06-12"
---

```{r}
#load libraries for coding
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readxl)
```

--------------------------------------------------------------------------------

```{r}
wcoa6 <- read_excel("~/NOAA Work/West Coast/WCOA-6/W06_SH1709R_djg_v2.xlsx")

wcoa6 <- wcoa6 %>% 
  janitor::clean_names() %>% 
  rename(stnnbr = station_id, ctdprs = ctdpressure_dbar, oxygen = oxygen_umol_kg, latitude = latitude_dec, longitude = longitude_dec, ctdoxy = ctdoxygen_umol_kg, 
         ctdtmp = ctdtmp_its90_deg_c, ctdsal = ctdsal_pss78, date = date_utc) %>% 
  filter(oxygen > 0 | ctdoxy > 0) %>%
  filter(oxygen_flag == 1 | oxygen_flag == 2 | oxygen_flag == 6) %>%
  mutate(oxygen = if_else(oxygen < 0, NA, oxygen)) %>% 
  mutate(ctdoxy = if_else(ctdoxy < 0, NA, ctdoxy)) %>%
  select(stnnbr, oxygen, ctdoxy, latitude, longitude, ctdtmp, ctdsal, ctdprs, date) %>% 
  mutate(cruise = rep("WCOA6", n())) %>%
  mutate(across(2:8, as.numeric))

write_csv(wcoa6, "~/NOAA Work/West Coast/WCOA-6/WCOA-6-CLEAN.csv")
```

--------------------------------------------------------------------------------
