---
title: "WCOA-7"
output: pdf_document
date: "2024-06-12"
---

```{r}
#load libraries
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readxl)
```

--------------------------------------------------------------------------------

```{r}
wcoa7 <- read_excel("~/NOAA Work/West Coast/WCOA-7/WCOA2021_Data_forSDIS_2022_09-28.xlsx")

wcoa7 <- wcoa7 %>% 
  slice(-1) %>% 
  janitor::clean_names() %>% 
  rename(stnnbr = station_id, ctdprs = ctdpres, oxygen = oxygen_djg, oxy = oxygen, ctdtmp = ctdtemp_its90, ctdsal = ctdsal_pss78) %>% 
  mutate(date = dmy(str_glue("{day_utc}, {month_utc}, {year_utc}"))) %>%
  filter(oxygen > 0 | ctdoxy > 0) %>%
  filter(oxygen_flag == 1 | oxygen_flag == 2 | oxygen_flag == 6) %>%
  mutate(oxygen = if_else(oxygen < 0, NA, oxygen)) %>% 
  mutate(ctdoxy = if_else(ctdoxy < 0, NA, ctdoxy)) %>%
  select(stnnbr, oxygen, ctdoxy, latitude, longitude, ctdtmp, ctdsal, ctdprs, date) %>% 
  mutate(cruise = rep("WCOA7", n())) %>%
  mutate(across(2:8, as.numeric))

write_csv(wcoa7, "~/NOAA Work/West Coast/WCOA-7/WCOA-7-CLEAN.csv")
```

--------------------------------------------------------------------------------






